language: node_js

node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  yarn: true

script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  # install Docusaurus and generate file of English strings
  - cd website && yarn install && yarn run write-translations && cd ..
  # crowdin install
  - sudo apt-get install default-jre
  - wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
  - sudo dpkg -i crowdin.deb
  # translations upload/download
  - crowdin --config crowdin.yaml upload sources --auto-update -b master
  - crowdin --config crowdin.yaml download -b master
  # build and publish website
  - yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
